const commonvar={
    /*FIREWORKS16 : `./resource/fireworks/Fireworks16_frame`,
     FIREWORKS3 : `./resource/fireworks/Fireworks3_frame`,
     LENSFLARE6 : `./resource/lensflare/LensFlare6_frame`,
     LENSFLARE7: `./resource/lensflare/LensFlare7_frame`,
     PARTICLES1 : `./resource/particles/Particles1_frame`,
     PARTICLES3 :`./resource/particles/Particles3_frame`,
     RAIN16 : `./resource/rain/RAIN16_frame`,
     RAIN18 : `./resource/rain/RAIN18_frame`,
     SMOKE4 :`./resource/smoke/Smoke4_frame`,
     SMOKE6 : `./resource/smoke/Smoke6_frame`,*/
     //ffmpeg Overlayss sourcess
     /*FIREWORKS16: `./resource/fireworks16.mp4`,
     FIREWORKS3: `./resource/fireworks3.mp4`,
     LENSFLARE6: `./resource/lensflaress6.mp4`,
     LENSFLARE7: `./resource/lensflaress7.mp4`,
     PARTICLES1: `./resource/particles1.mp4`,
     PARTICLES3: `./resource/particles3.mp4`,
     RAIN16: `./resource/rain16.mp4`,
     RAIN18: `./resource/rain18.mp4`,
     SMOKE4: `./resource/smoke4.mp4`,
     OVERLAY1: `./resource/overlay1.gif`,
     OVERLAY2: `./resource/overlay2.gif`,
     OVERLAY3: `./resource/overlay3.gif`,*/
     "fireworks16_.gif":`./resource/fireworks16_.gif`,
     "fireworks3_.gif":`./resource/fireworks3_.gif`,
     "smoke4_.gif":`./resource/smoke4_.gif`,
     "lensflaress6_.gif":`./resource/lensflaress6_.gif`,
     "lensflaress7_.gif":`./resource/lensflaress7_.gif`,
     "particles1_.gif":`./resource/particles1_.gif`,
     "rain16_.gif":`./resource/rain16_.gif`,
     "rain18_.gif":`./resource/rain18_.gif`,
     "particles3_.gif":`./resource/particles3_.gif`,
     "overlay1.gif":`./resource/overlay1.gif`,
     "overlay2.gif":`./resource/overlay2.gif`,
     "overlay3.gif":`./resource/overlay3.gif`,
     "overlay4.gif":`./resource/overlay4.gif`,
     //MUSIC1 : `./resource/test1_1.mp3`,
     //MUSIC2 : `./resource/test1_2.mp3`,
     //MUSIC3 : `./resource/test1_3.mp3`,
     //Music sourcess
     MUSIC1: `./resource/cllap_music1.mp3`,
     MUSIC2: `./resource/cllap_music2.mp3`,
     MUSIC3: `./resource/cllap_music3.mp3`,
     MUSIC4 : `./resource/test2_1_.mp3`,
     MUSIC5 : `./resource/test2_2_.mp3`,
     MUSIC6 : `./resource/test2_3_.mp3`,
     MUSIC7 : `./resource/test3_1_.mp3`,
     MUSIC8 : `./resource/test3_2_.mp3`,
     MUSIC9 : `./resource/test3_3_.mp3`,
     MUSIC10 : `./resource/test4_1_.mp3`,
     MUSIC11 : `./resource/test4_2_.mp3`,
     MUSIC12 : `./resource/test4_3_.mp3`,

     //ffmpeg complex_filter effect string sourcess
     COLOR_RED: `colorbalance=rh=0.6:rs=0.6`,
     COLOR_BLUE: `colorbalance=bh=0.6:bs=0.6`,
     COLOR_GREEN: `colorbalance=gh=0.6:gs=0.6`,
     COLOR_YELLOW: "colorbalance=rh=0.6:gh=0.6:rs=0.6:gs=0.6",
     COLOR_BLUEPURPLE: "colorbalance=rs=0.5:bs=0.8:rh=0.5:bh=0.8",
     COLOR_REDPURPLE: "colorbalance=rh=0.8:bh=0.5:rs=0.8:bs=0.5",
     COLOR_PINKPURPLE: "colorbalance=rh=0.6:bh=0.6:rs=0.6:bs=0.6",
     COLOR_PURPLE: "colorbalance=rh=0.4:bh=0.7:rs=0.4:bs=0.7",
     COLOR_BLUEGREEN: "colorbalance=gh=0.8:bh=0.5:gs=0.8:bs=0.5", 
     COLOR_CYAN: "colorbalance=gh=0.5:bh=0.8:gs=0.5:bs=0.8", 
     COLOR_LIGHTBLUE: "colorbalance=gh=0.3:bh=0.3:gs=0.3:bs=0.3", 
     COLOR_GREENBLUE: "colorbalance=gh=0.3:bh=0.6:gs=0.3:bs=0.6",
     COLOR_WHITE:  "colorbalance=rh=0.7:gh=0.7:bh=0.7:rs=0.7:gs=0.7:bs=0.7" ,

     CONV_laplacian: "convolution='0 1 0 1 -4 1 0 1 0:0 1 0 1 -4 1 0 1 0:0 1 0 1 -4 1 0 1 0:0 1 0 1 -4 1 0 1 0:5:5:5:1:0:128:128:128'",
     CONV_edgeenhance: "convolution='0 0 0 -1 1 0 0 0 0:0 0 0 -1 1 0 0 0 0:0 0 0 -1 1 0 0 0 0:0 0 0 -1 1 0 0 0 0:5:1:1:1:0:128:128:128'",
     CONV_edgedetect: "convolution='0 1 0 1 -4 1 0 1 0:0 1 0 1 -4 1 0 1 0:0 1 0 1 -4 1 0 1 0:0 1 0 1 -4 1 0 1 0:5:5:5:1:0:128:128:128'",  
     CONV_emboss: "convolution='-2 -1 0 -1 1 1 0 1 2:-2 -1 0 -1 1 1 0 1 2:-2 -1 0 -1 1 1 0 1 2:-2 -1 0 -1 1 1 0 1 2'",

     CURVE_vintage: "curves=r='0/0.11 .42/.51 1/0.95':g='0/0 0.50/0.48 1/1':b='0/0.22 .49/.44 1/0.8'",
     CURVE_negative: "curves=preset=color_negative",
     CURVE_crossprocess: "curves=preset=cross_process",

     GRID_Bisque: "drawgrid=width=100:height=100:thickness=3:color=Bisque@0.6",
     GRID_Brown: "drawgrid=width=100:height=100:thickness=3:color=Brown@0.6",
     GRID_BurlyWood: "drawgrid=width=100:height=100:thickness=3:color=BurlyWood@0.6",
     GRID_Chocolate: "drawgrid=width=100:height=100:thickness=3:color=Chocolate@0.6",
     GRID_DarkCyan: "drawgrid=width=100:height=100:thickness=3:color=DarkCyan@0.6",
     GRID_DarkSalmon: "drawgrid=width=100:height=100:thickness=3:color=DarkSalmon@0.6",
     GRID_DeepSkyBlue: "drawgrid=width=100:height=100:thickness=3:color=DeepSkyBlue@0.6",
     GRID_FireBrick: "drawgrid=width=100:height=100:thickness=3:color=FireBrick@0.6",
     GRID_HotPink: "drawgrid=width=100:height=100:thickness=3:color=HotPink@0.6",
     GRID_ForestGreen: "drawgrid=width=100:height=100:thickness=3:color=ForestGreen@0.6",
     GRID_LavenderBlush: "drawgrid=width=100:height=100:thickness=3:color=LavenderBlush@0.6",
     GRID_LightPink: "drawgrid=width=100:height=100:thickness=3:color=LightPink@0.6",
     
     GEQ_rgbshow: `geq=r='X/W*r(X,Y)':g='(1-X/W)*g(X,Y)':b='(H-Y)/H*b(X,Y)'`,

     HUE_colorshow: `hue='H=2*PI*t:s=sin(2*PI*t)+1'`,

     Pseudocolor_magma: `pseudocolor=preset='magma'`,
     Pseudocolor_inferno: `pseudocolor=preset='inferno'`,
     Pseudocolor_plasma: `pseudocolor=preset='plasma'`,
     Pseudocolor_viridis: `pseudocolor=preset='viridis'`,
     Pseudocolor_turbo: `pseudocolor=preset='turbo'`,
     Pseudocolor_shadows: `pseudocolor=preset='shadows'`,
     //Pseudocolor_solar: `pseudocolor=preset='solar'`,

     Rotate_default: `rotate=PI/3+2*PI*t/3`,
     Rotate_slow: `rotate=0.26*sin(2*PI/3*t)`,
     Rotate_fast: `rotate=6.86*sin(2*PI/3*t)`,

     //Trippy: "=lagfun",

     TRANSITON_EFFECT : {
         '1_transition' : 'dissolve',
         '2_transition' : 'radial',
         '3_transition' : 'circleopen',
         '4_transition' : 'pixelize',
         '5_transition' : 'vuslice',
         '6_transition' : 'hblur',
         '7_transition' : 'fadegrays',
         '108_transition' : 'fadeblack',
         '109_transition' : 'rectcrop',
         '110_transition' : 'circlecrop',
         '111_transition' : 'slideup',
         '112_transition' : 'slideright',

         '8_transition':'hlslice',
         '9_transition':'hrslice',
         '10_transition':'vuslice',
         '11_transition':'vdslice',
         '12_transition':'fadewhite',
         '13_transition':'wipeleft',
         '14_transition':'wiperight',
         '15_transition':'slidedown',
         '16_transition':'distance',
         '17_transition':'diagtl',

     },
     OPENCVTRANSITION : {
         "108_opencv" : "transition_cut_",
         "109_opencv" : "transition_Rotation_left",
         "110_opencv" : "transition_Rotation_right",
         "111_opencv" : "transition_glitch_",
         "112_opencv" : "transition_glitch_"
     }

}

module.exports= commonvar;